# Generated by Django 2.2.3 on 2019-07-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=50)),
                ('cusCode', models.IntegerField()),
                ('cusPhoneNum', models.CharField(max_length=50)),
                ('cusBirthDate', models.DateTimeField()),
                ('cusSex', models.CharField(max_length=50)),
                ('cusRemarks', models.CharField(max_length=200)),
            ],
        ),
    ]
