# Generated by Django 2.2.3 on 2019-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cusBirthDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cusCode',
            field=models.CharField(max_length=50),
        ),
    ]
