# Generated by Django 2.2.3 on 2019-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0003_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=50)),
                ('empCode', models.CharField(max_length=50)),
                ('empBirthDate', models.DateField()),
                ('empPhoneNum', models.CharField(max_length=50)),
                ('empAdd', models.CharField(max_length=100)),
            ],
        ),
    ]
