# Generated by Django 2.2.3 on 2019-07-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cusBirthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empBirthDate',
            field=models.DateField(null=True),
        ),
    ]
