# Generated by Django 2.2.3 on 2019-07-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0005_auto_20190728_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='cusBirthDate',
        ),
        migrations.AlterField(
            model_name='customers',
            name='cusRemarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
