# Generated by Django 2.2.3 on 2019-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0006_auto_20190728_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stockQua',
            field=models.IntegerField(null=True),
        ),
    ]
