# Generated by Django 2.2.3 on 2019-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0007_stock_stockqua'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comCode', models.CharField(max_length=50)),
                ('comStockCode', models.CharField(max_length=50)),
            ],
        ),
    ]
