# Generated by Django 2.2.3 on 2019-08-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0008_combinestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDate', models.DateField()),
                ('saleId', models.CharField(max_length=50)),
                ('saleCusId', models.CharField(max_length=50)),
                ('saleStockId', models.CharField(max_length=50)),
                ('saleShopId', models.CharField(max_length=50)),
                ('saleQua', models.IntegerField()),
                ('salePrice', models.IntegerField()),
                ('saleEmp', models.CharField(max_length=50)),
                ('salePoint', models.IntegerField()),
                ('saleRemark', models.CharField(max_length=100)),
            ],
        ),
    ]
