# Generated by Django 2.2.3 on 2019-08-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0009_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='saleCusId',
            new_name='saleCode',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='saleId',
            new_name='saleCusCode',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='saleShopId',
            new_name='saleShopCode',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='saleStockId',
            new_name='saleStockCode',
        ),
    ]
