# Generated by Django 2.2.3 on 2019-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0011_auto_20190814_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='saleDate',
            field=models.DateField(null=True),
        ),
    ]
