# Generated by Django 2.2.3 on 2019-08-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0012_auto_20190814_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='saleEmp',
            new_name='saleEmpCode',
        ),
    ]
