# Generated by Django 2.2.3 on 2019-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0013_auto_20190814_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='setSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setDate', models.DateField()),
                ('setCode', models.CharField(max_length=50)),
                ('setCusCode', models.CharField(max_length=50)),
                ('setStockCode', models.CharField(max_length=50)),
                ('setShopCode', models.CharField(max_length=50)),
                ('setEmpCode', models.CharField(max_length=50)),
                ('setPrice', models.IntegerField()),
                ('setRemark', models.CharField(max_length=100)),
            ],
        ),
    ]
