# Generated by Django 2.2.3 on 2019-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0015_cusownset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setsale',
            name='setEmpCode',
        ),
        migrations.AddField(
            model_name='setsale',
            name='setEmp1Code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setsale',
            name='setEmp2Code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setsale',
            name='setEmp3Code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setCusCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setRemark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setShopCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setsale',
            name='setStockCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
