# Generated by Django 2.2.3 on 2019-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0016_auto_20190822_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='setsale',
            name='setSaleCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
