# Generated by Django 2.2.3 on 2019-08-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0017_setsale_setsalecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setsale',
            name='setStockCode',
        ),
    ]
