# Generated by Django 2.2.3 on 2019-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0018_remove_setsale_setstockcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50)),
                ('shopCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='cusShopCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stockShopCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
