# Generated by Django 2.2.3 on 2019-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0019_auto_20190829_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empClass',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
