# Generated by Django 2.2.3 on 2019-09-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0020_employee_empclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empShop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
