# Generated by Django 2.2.3 on 2019-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0021_employee_empshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inStockCode', models.CharField(max_length=50)),
                ('inStockShopCode', models.CharField(max_length=50)),
                ('inStockQua', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stockQua',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stockShopCode',
        ),
    ]
