# Generated by Django 2.2.3 on 2019-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0022_auto_20190902_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='importReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importCode', models.CharField(max_length=50)),
                ('importStockCode', models.CharField(max_length=50)),
                ('importFromShopCode', models.CharField(max_length=50)),
                ('importToShopCode', models.CharField(max_length=50)),
                ('importQua', models.IntegerField()),
            ],
        ),
    ]
