# Generated by Django 2.2.3 on 2019-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0023_importreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commName', models.CharField(max_length=50)),
                ('commCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_commCode', models.CharField(max_length=50)),
                ('CLIncomeLimit', models.IntegerField()),
                ('CLBonusPercent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultiSevicePercnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSPName', models.CharField(max_length=50)),
                ('MSPCode', models.CharField(max_length=50)),
                ('MSPemp1', models.IntegerField()),
                ('MSPemp2', models.IntegerField()),
                ('MSPemp3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='regularBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonusName', models.CharField(max_length=50)),
                ('bonusCode', models.CharField(max_length=50)),
                ('bonusLowLimit', models.IntegerField()),
                ('bonusValue', models.IntegerField()),
            ],
        ),
    ]
