# Generated by Django 2.2.3 on 2019-09-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0025_remove_regularbonus_bonuslowlimit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiSevicePercnet',
            new_name='MultiSevicePercent',
        ),
    ]
