# Generated by Django 2.2.3 on 2019-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0026_auto_20190921_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='commlimit',
            name='CLCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
