# Generated by Django 2.2.3 on 2019-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0027_commlimit_clcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commlimit',
            name='comm_commCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
