# Generated by Django 2.2.3 on 2019-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0028_auto_20190922_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commlimit',
            name='comm_commCode',
            field=models.CharField(max_length=50),
        ),
    ]
