# Generated by Django 2.2.3 on 2019-09-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0029_auto_20190922_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySelectEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSEEmpCode', models.CharField(max_length=50)),
            ],
        ),
    ]
