# Generated by Django 2.2.3 on 2019-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0030_salaryselectemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='saleType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setsale',
            name='setType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
