# Generated by Django 2.2.3 on 2019-09-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0031_auto_20190927_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='setsale',
            name='setPoint',
            field=models.IntegerField(null=True),
        ),
    ]
