# Generated by Django 2.2.3 on 2019-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFormalTest', '0032_setsale_setpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRempName', models.CharField(max_length=50)),
                ('SRsalary', models.IntegerField()),
                ('SRpoint', models.IntegerField()),
                ('SRpoint1', models.IntegerField()),
                ('SRpoint2', models.IntegerField()),
                ('SRpoint3', models.IntegerField()),
                ('SRstockIncomeComm', models.IntegerField()),
                ('SRincome', models.IntegerField()),
                ('SRSCIncomeComm', models.IntegerField()),
                ('SRSCIncome', models.IntegerField()),
                ('SRbarberIncomeComm', models.IntegerField()),
                ('SRbarberIncome', models.IntegerField()),
                ('SRresult', models.IntegerField()),
            ],
        ),
    ]
